mqConsumer:
  queueName: "request_logs"
  connectionString: "amqp://guest:guest@localhost:5672/"

clickHouse:
  database: "science-archive"
  host: "127.0.0.1:9000"
  username: "default"
  password: ""