name: Dev branch

on:
  push:
    branches:
    - dev

jobs:
  check_changed_files:
    runs-on: ubuntu-latest
    name: Check changes files
    steps:


  build:
    runs-on: ubuntu-latest
    name: Build frontend
    steps:
    - uses: actions/checkout@v1
